### ISSUE TITLE
Entry point should be racket, not DrRacket 

### ISSUE THREAD

**Issue by spdegabrielle** [flathub/org.racket_lang.DrRacket#2]
Hi

the entry point for the racket distribution is `racket` not DrRacket

This is clear in the first page of the Racket Guide

https://docs.racket-lang.org/guide/intro.html

making DrRacket is the equivalent of making IDLE the entry point for the Python language, because it is a bundles IDE.

Best regards

Stephen

**Comment by spdegabrielle** [comment]
@capfredf please mention the reviewer responsible for this

**Comment by capfredf** [comment]
Hi @spdegabrielle , 

As I mentioned on discord and discourse, [the entry point](https://github.com/flathub/org.racket_lang.DrRacket/blob/master/org.racket_lang.DrRacket.yml#L5) of this flatpak should be consistent with how we start the application. 

I agree the the id 'org.racket_lang.DrRacket` is not desireable.

**Comment by capfredf** [comment]
The id is not changeable.

**Comment by spdegabrielle** [comment]
> Hi @spdegabrielle ,
> 
> As I mentioned on discord and discourse, [the entry point](https://github.com/flathub/org.racket_lang.DrRacket/blob/master/org.racket_lang.DrRacket.yml#L5) of this flatpak should be consistent with how we start the application.

Racket is started with `racket`;

> [Download Racket](https://download.racket-lang.org/), install, and then start racket with no command-line arguments:
```
$ racket
--
Welcome to Racket v8.7 [cs].
>
```
(from  https://docs.racket-lang.org/more/index.html )

If this flatpack is intended to be for DrRacket then maybe that should be the name for the flatpack?

best regards
Stephen

***

## note 

Should the description note that the flatpack includes the full racket distribution?

* **`racket`**, (the core compiler, interpreter, and run-time system);
* **DrRacket**, the programming environment; 
* `raco`, a set of command-line tool; 
* the **Scribble** document production system; 
* the **Slideshow** presentation application; 
* and a collection of gui games.

**Comment by capfredf** [comment]
`flatpak run <whatever-id-we-use>` should open an DrRacket instance, which is result you will get when you click DrRacket the icon in gnome's `Activities`. 

To run other executables, we could do `flatpak run <whatever-id-we-use> --command <command>` .

**Comment by capfredf** [comment]
see https://github.com/flathub/org.racket_lang.Racket
